-- Q1. What is the total revenue generated by male vs. female customers?
select sum(`purchase_amount_(usd)`), gender from customer group by(gender);

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id , `purchase_amount_(usd)` from customer
where discount_applied = 'Yes' and `purchase_amount_(usd)` > (select avg(`purchase_amount_(usd)`) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as avg_ratings
from customer group by item_purchased
order by avg_ratings desc limit 10;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type , round(avg(`purchase_amount_(usd)`),2) as avg_purchase_amount
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
Select subscription_status, round(avg(`purchase_amount_(usd)`),2) as avg_total_spend,
count(customer_id) as total_customer,  round(sum(`purchase_amount_(usd)`),2) as total_revenue
from customer
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased as products, 
Round((100 * sum(case when discount_applied = 'Yes' Then 1 Else 0 END))/count(*),2) as total_buying 
from customer group by item_purchased order by total_buying desc limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous 
-- purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case 
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
when previous_purchases >= 10 then 'Loyal'
end as customer_segment
from customer
)
select customer_segment, count(*) as 'Number of Customer'
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
with most_purchased_products as (
select category, item_purchased, count(customer_id) as total_customer,
row_number() over(partition by category order by count(customer_id) desc) as rank_of_product
from customer group by category, item_purchased
)
select category, item_purchased, total_customer, rank_of_product from most_purchased_products 
where rank_of_product <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(customer_id) as total_customers, subscription_status
from customer where previous_purchases > 5 group by subscription_status;


-- Q10. What is the revenue contribution of each age group?
select count(customer_id) as total_customer,
 sum(`purchase_amount_(usd)`) as total_revenue,
 age_group
 from customer
 group by age_group
 order by total_revenue desc;